version: "3"
services:
  docusaurus:
    working_dir: /data
    restart: unless-stopped
    image: docs-dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    logging:
      driver: json-file
      options:
        max-size: 50m
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/data/
    command: yarn start --host 0.0.0.0